more @SuppressionWarnings cleanup
typetools/guava pull request #71
Opened 2023-05-01 22:41 UTC by markro49

2023-05-13 16:16 UTC, mernst requested changes
In AtomicDouble.java, I was able to reduce the number of warning suppressions by removing them on a number of clients, and adding one on the method that all the clients call.

I removed the @PolyValue annotations on LongAdder that were technically true, but I don't see how they would ever be useful to a client, and they were not statically verifiable.

I fixed a Signedness Checker bug in https://github.com/typetools/checker-framework/pull/5862.  (This accounts for much of my delay in reviewing this; sorry about that.  Thank you for noticing the bug.)

When an explicit cast appears, I think it's better to write the type annotation on that cast.  By contrast, a suppression on the return value requires the reader to reason about what the effective cast type is and why it does not type-check.

2023-05-14 00:17 UTC, markro49 commented on guava/src/com/google/common/primitives/Booleans.java
> +  public static @LTEqLengthOf("#1") int indexOf(boolean[] array, boolean[] target) {
src/com/google/common/primitives/Booleans.java:203: warning: [[index, substringindex, allcheckers]:anno.on.irrelevant] Annotation [@SubstringIndexFor(value = "#1", offset = "#2.length - 1")] is not applicable to int

2023-05-14 00:19 UTC, markro49 commented on guava/src/com/google/common/primitives/Bytes.java
> +  public static @LTEqLengthOf("#1") int indexOf(@PolySigned byte[] array, @PolySigned byte[] target) {
src/com/google/common/primitives/Bytes.java:132: warning: [[index, substringindex, allcheckers]:anno.on.irrelevant] Annotation [@SubstringIndexFor(value = "#1", offset = "#2.length - 1")] is not applicable to int

2023-05-14 00:33 UTC, markro49 commented on guava/src/com/google/common/primitives/UnsignedInts.java
> +  @SuppressWarnings("signedness:return") // needs Unsigned cast, but then cast.unsafe warning
I agree - will revert change.

2023-05-14 00:42 UTC, markro49 commented on guava/src/com/google/common/primitives/UnsignedInteger.java
> +  @SuppressWarnings("value:return") // needs PolyValue cast, but then cast.unsafe warning
I agree - reverted change.

2023-05-14 13:58 UTC, markro49 commented on guava/src/com/google/common/primitives/Bytes.java
> +  @SuppressWarnings("signedness:return") // needs PolySigned cast, but then cast.unsafe warning
This suppression is unneeded and will be removed.

2023-05-14 14:00 UTC, markro49 commented on guava/src/com/google/common/primitives/Bytes.java
> +    @SuppressWarnings("signedness:assignment") // signedness is ok
This suppression is unneeded and will be removed.

2023-05-14 15:05 UTC, markro49 commented on guava/src/com/google/common/primitives/Bytes.java
> +  @SuppressWarnings("signedness:return") // needs PolySigned cast, but then cast.unsafe warning
added casts and changed comments

2023-05-14 21:01 UTC, mernst approved these changes

2023-05-14 21:01 UTC, merged